language: python
git:
    quiet: true
    submodules: false
branches:
    only:
        - /.*/
python:
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'
script:
    - chmod 744 lint.sh && ./lint.sh
    - cd unit_tests
    - python3 cmake-tidy_test.py
