# vim: nospell

language: python
git:
  quiet: true
  submodules: false
branches:
  only:
    - /.*/
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'

install:
  - |
    if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]
    then
      pip install --quiet --requirement ci-requirements.txt
    fi

script:
  - |
    if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]
    then
      black --check .
      pylint bin/cmake-tidy
      pylint cmake_tidy
      lizard --CCN=10 --length=20 --arguments=6 --warnings_only --modified
    fi
  #- chmod 744 lint.sh && ./lint.sh
