# vim: nospell

language: python
git:
  quiet: true
  submodules: false
branches:
  only:
    - /.*/
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'

install:
  - pip install --quiet --requirement ci-requirements.txt

script:
  - black --check .
  #- chmod 744 lint.sh && ./lint.sh
